### ISSUE TITLE
Header isn't read 

### ISSUE THREAD

**Issue by SourceCodeDeleted** [KodaSec/wince-extractor#5]
I get this with every winCE file that I test. 
I tested against these old files. 

https://forum.xda-developers.com/t/nk-bin-and-dumprom.656086/?__cf_chl_jschl_tk__=D2uAXTkdfKd1Y3SVgHH3ka3tCpQxGJyAN1o60NbeGBo-1636038001-0-gaNycGzNChE  

 ```
 File "/home/user/works/wince-extractor/winceextractor.py", line 823, in <module>
    with WinCEExtractor(f, image_offset) as extractor:
  File "/home/user/works/wince-extractor/winceextractor.py", line 498, in __enter__
    self.analyze()
  File "/home/user/works/wince-extractor/winceextractor.py", line 519, in analyze
    romhdr_s = load_from_offset(self.data, self.romhdr_offset, RomHdr)
  File "/home/user/works/wince-extractor/winceextractor.py", line 431, in load_from_offset
    return structure.from_buffer_copy(data[offset:offset + ctypes.sizeof(structure)])
ValueError: Buffer size too small (0 instead of at least 84 bytes)
```

**Comment by SourceCodeDeleted** [comment]
@ArtificialAmateur here I opened an issue.

Is this something you can help with please ?

**Comment by ArtificialAmateur** [comment]
The target files are for ARM, the wince decompression only tool targets the x86-specific compression algorithm that does additional preprocessing. It might be worth testing without the relative call opcode preprocessing.

Closing until a patch is submitted.
